dist: focal
language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '13'
matrix:
  fast_finish: true
script:
  - npm run check-source-formatting
  - npm run lint
  - npm run check-types
  - npm run build
  - npm run test
